adversary_list:
- 0
alpha_loss: 1.0
baseline: false
batch_size: 64
clamp_value: 1.0
current_time: Nov.21_15.05.45
decay: 0.0005
diff_privacy: false
dirichlet_alpha: 0.9
environment_name: ppdl_experiment
epochs: 1
eta: 1
fake_participants_file: data/reddit/updates_cifar.pt.tar
fake_participants_load: false
fake_participants_save: false
folder_path: saved_models/model_image_Nov.21_15.05.45
is_poison: true
log_interval: 10
lr: 0.1
momentum: 0.9
no_models: 5
noise_level: 0.01
number_of_adversaries: 1
number_of_total_participants: 20
poison_decay: 0.005
poison_epochs:
- 1
poison_images:
- 30696
- 33105
- 33615
- 33907
- 36848
- 40713
- 41706
poison_images_test:
- 330
- 568
- 3934
- 12336
- 30560
poison_label_swap: 2
poison_lr: 0.05
poison_momentum: 0.9
poison_step_lr: true
poison_type: wall
poisoned_number: 2
poisoning_per_batch: 1
random_compromise: false
report_poison_loss: false
report_test_loss: false
report_train_loss: false
results_json: false
resumed_model: null
retrain_no_times: 2
retrain_poison: 2
s_norm: 1000000
sampling_dirichlet: false
save_model: true
save_on_epochs:
- 1
scale_weights: 100
size_of_secret_dataset: 10
test_batch_size: 20
track_clusters: false
track_distance: false
type: image
